package quizkampen;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class Resultview {

    public static void main(String[] args) {
        
        JFrame f = new JFrame("Ouizkampen");
        f.setBackground(Color.BLUE);
        JPanel p0 = new JPanel();
        p0.setLayout(new BoxLayout(p0, BoxLayout.Y_AXIS));
        p0.setBackground(Color.BLUE);
        f.add(p0);
            JPanel title = new JPanel(new GridLayout(0,1));
                title.setBackground(Color.BLUE);
                JLabel main = new JLabel("QuizKampen"); 
                    main.setHorizontalAlignment(JLabel.CENTER);
                    title.add(main);
        p0.add(title);
            JPanel p = new JPanel(new GridLayout(0,5));
                p.setBackground(Color.BLUE);
                JPanel one = new JPanel(new GridLayout(0,1));
                    one.setBackground(Color.BLUE);
                    JLabel a = new JLabel("Användare ett");
                        a.setHorizontalAlignment(JLabel.RIGHT);
                JPanel two = new JPanel(new GridLayout(0,1));    
                    two.setBackground(Color.BLUE);
                    JLabel b = new JLabel("2");
                        b.setHorizontalAlignment(JLabel.CENTER);
                JPanel three = new JPanel(new GridLayout(0,1));    
                    three.setBackground(Color.BLUE);
                    JLabel c = new JLabel(" - ");
                        c.setHorizontalAlignment(JLabel.CENTER);
                JPanel four = new JPanel(new GridLayout(0,1));        
                    four.setBackground(Color.BLUE);
                    JLabel d = new JLabel("3");
                        d.setHorizontalAlignment(JLabel.CENTER);
                JPanel five = new JPanel(new GridLayout(0,1));    
                    five.setBackground(Color.BLUE);
                    JLabel e = new JLabel("Användare två");
                        e.setHorizontalAlignment(JLabel.CENTER);
                    one.add(a);    
                    two.add(b);    
                    three.add(c);    
                    four.add(d);    
                    five.add(e);        
                    p.add(one);
                    p.add(two);
                    p.add(three);
                    p.add(four);
                    p.add(five);
            p0.add(p);
            JPanel p2 = new JPanel(new GridLayout(0,1));
                p2.setBackground(Color.BLUE);
                JLabel p21 = new JLabel("Rond 1");
                    p21.setHorizontalAlignment(JLabel.CENTER);
                    p2.add(p21);
                    p0.add(p2); 
            JPanel p3 = new JPanel(new GridLayout(0,3));
                    p3.setBackground(Color.BLUE);
                JPanel p31 = new JPanel(new GridLayout(0,2));
                        JButton d1 = new JButton();
                            d1.setBackground(Color.RED);
                            d1.setPreferredSize(new Dimension(300, 60));
                        JButton d2 = new JButton();
                            d2.setBackground(Color.RED);
                            d2.setPreferredSize(new Dimension(300, 60));
                            p31.add(d1);
                            p31.add(d2);
                            p3.add(p31);
                JPanel p32 = new JPanel(new GridLayout(0,1));
                    p32.setBackground(Color.BLUE);
                        JLabel aa = new JLabel("Ämne");
                            aa.setHorizontalAlignment(JLabel.CENTER);
                            p32.add(aa);
                            p3.add(p32);     
                JPanel p33 = new JPanel(new GridLayout(0,2));
                        JButton f1 = new JButton();
                            f1.setBackground(Color.GREEN);
                            f1.setPreferredSize(new Dimension(300, 60));
                        JButton f2 = new JButton();
                            f2.setBackground(Color.GREEN);
                            f2.setPreferredSize(new Dimension(300, 60));
                            p33.add(f1);
                            p33.add(f2);
                            p3.add(p33);
            p0.add(p3);  
            JPanel p4 = new JPanel(new GridLayout(0,3));
                p4.setBackground(Color.BLUE);
                p4.add(new JLabel(""));
                JLabel g = new JLabel("Round 2");
                    g.setHorizontalAlignment(JLabel.CENTER);
                    p4.add(g);
                    p4.add(new JLabel(""));
            p0.add(p4);
            JPanel p5 = new JPanel(new GridLayout(0,3));
                p5.setBackground(Color.BLUE);
                    JPanel p51 = new JPanel(new GridLayout(0,2));
                        JButton h1 = new JButton();
                            h1.setBackground(Color.GREEN);
                            h1.setPreferredSize(new Dimension(300, 60));
                        JButton h2 = new JButton();
                            h2.setBackground(Color.RED); 
                            h2.setPreferredSize(new Dimension(300, 60));
                            p51.add(h1);
                            p51.add(h2);
                            p5.add(p51);
                    JLabel i = new JLabel("Ämne");
                        i.setHorizontalAlignment(JLabel.CENTER);
                    p5.add(i);
                    JPanel p52 = new JPanel(new GridLayout(0,2));    
                        JButton j1= new JButton();
                            j1.setBackground(Color.RED);
                            
                        JButton j2= new JButton();
                            j2.setBackground(Color.GREEN);
                            j2.setPreferredSize(new Dimension(300, 60));
                            p52.add(j1);
                            p52.add(j2);
                            p5.add(p52);
            p0.add(p5);
            JPanel p6 = new JPanel(new GridLayout(0,3));
                p6.setBackground(Color.BLUE);
                    JPanel p61 = new JPanel (new GridLayout(0,5));
                        JLabel tom = new JLabel(" ");
                        JLabel tom2 = new JLabel(" ");
                        p61.setBackground(Color.BLUE);
                        JButton k1 = new JButton("Ge upp");
                            k1.setBackground(Color.RED);
                            k1.setPreferredSize(new Dimension(300, 60));
                    JPanel p62 = new JPanel (new GridLayout(0,5));
                        JLabel tomt = new JLabel(" ");
                        JLabel tomt2 = new JLabel(" ");
                        p62.setBackground(Color.BLUE);
                        JButton k2 = new JButton("SPELA");
                            k2.setBackground(Color.GREEN);
                            k2.setPreferredSize(new Dimension(300, 60));
                            p61.add(tom);
                            p61.add(tom2);
                            p61.add(k1);
                            p62.add(tomt);
                            p62.add(tomt2);
                            p62.add(k2);
                            p5.add(p61);
                            p5.add(p62);
            p0.add(p5);            
        f.pack();
        f.setLocation(300, 300);
        f.setVisible(true);
    }
}

